### ISSUE TITLE
Inform people of the Student Program for US-RSE24 due 2024-09-12

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#102]
**Request type**: 

- [ ] Social media blast (LinkedIn, Mastodon, X/Twitter)

**Email** jamil-gafur@uiowa.edu

**Purpose** Inform people of the Student Program for US-RSE24

**Content**  https://docs.google.com/document/d/1PUJZNHooUfrZvYruYsBHDWU3Do0qFEyiuMCC531DwQk/edit#heading=h.zaq26e895xf2 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
I'm kind of confused about this request. The copy (which is page 2?) seems a lot more like an email than a social media post, but the request is to post on social media?

**Comment by KristinaRiemer** [comment]
This is supposed to be an email blast, both to US-RSE/conf, and to lots of universities.

**Comment by KristinaRiemer** [comment]
Send directly to student registrants too?

**Comment by KristinaRiemer** [comment]
We are not doing this anymore, it's just going to student registrants.
