### ISSUE TITLE
Wide Advertising Burst due 2024-09-11

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#105]
**Request type**: Email to conference listserv, Add to monthly US-RSE newsletter, Email to all US-RSE members

**Email** mmundt@sandia.gov

**Purpose** Wide Advertising Burst

**Content**  https://docs.google.com/document/d/1kkvz-jBJYEphB7aZ1MBqcpP3w8bTv58orVAxBPddtnc/edit 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
Including wider advertising list as per [this Slack message](https://usrse.slack.com/archives/C06C18R5KP1/p1726067037519469).

**Comment by jsubida** [comment]
This round of advertising is complete. Marking as done.

**Comment by KristinaRiemer** [comment]
Didn't we actually do it twice? 💪

**Comment by jsubida** [comment]
Marking this as doubly done then!
