### ISSUE TITLE
Inform Folks of Nuclear History Museum Event due 2024-09-23

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#115]
**Request type**: 

- [x] Website change / addition
- [ ] Add to monthly US-RSE newsletter
- [ ] Email to all US-RSE members
- [x] Social media blast (LinkedIn, Mastodon, X/Twitter), Slack
- [x] News item on conference website (see bottom of main page: https://us-rse.org/usrse24/)

**Email** mmundt@sandia.gov

**Purpose** Inform Folks of Nuclear History Museum Event

**Content**  https://docs.google.com/document/d/1l-VbXq5K6MHC3vuc2bNcA42oGo7hehwR9Iltl2mqyhw/edit 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
I'm going to consider this good at this point @mmundt.
