### ISSUE TITLE
Send a pre-conference email on behalf of Sandia, a platinum sponsor due 2024-09-23

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#118]
**Request type**: 

- [x] Email to conference listserv

**Email** aheinlei@umich.edu

**Purpose** Send a pre-conference email on behalf of Sandia, a platinum sponsor

**Content**  https://docs.google.com/document/d/1wBjJyFL_liCT8qJFrtEXMD972o8lDCvB/edit (Note that it's just the part in the "Email" section) 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
Sent 9/23/2024
