### ISSUE TITLE
Send a pre-conference email on behalf of GitLab, a gold sponsor due 2024-09-30

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#121]
**Request type**: Email to conference listserv

**Email** aheinlei@umich.edu

**Purpose** Send a pre-conference email on behalf of GitLab, a gold sponsor

**Content**  https://docs.google.com/document/d/1HjGLJGPaUZemFdiOBjTwfy7Udu9-tpYMeXJkj4Rlg6g/edit 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
Email sent 9/30!
