### ISSUE TITLE
Sponsor pre-conference email from Covalent Cloud (gold sponsor) due 2024-10-07

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#126]
**Request type**: Email to conference listserv

**Email** aheinlei@umich.edu

**Purpose** Sponsor pre-conference email from Covalent Cloud (gold sponsor)

**Content**  https://docs.google.com/document/d/1iNgp9B-Jvup5RuM64kQi_bNcwUmXbp-3/edit#heading=h.gjdgxs 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by mrmundt** [comment]
This is complete.
