### ISSUE TITLE
Notification About Ice-Cream Social due 2024-10-11

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#129]
**Request type**: Website change / addition, Email to conference listserv, Social media blast (LinkedIn, Mastodon, X/Twitter), Slack

**Email** ayush@wustl.edu

**Purpose** Notification About Ice-Cream Social

**Content**  https://docs.google.com/document/d/108o4nVnnG_AC439mfdrB1gfuIqhdYmWqKjzYAHzgJHw/edit?usp=sharing 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by mrmundt** [comment]
Not the responsibility of the Comms committee.
