### ISSUE TITLE
Update on deadline due 2024-05-31

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#49]
**Request type**: 
- [x] Email to conference listserv
- [x] Email to all US-RSE members
- [x] Social media blast (LinkedIn, Mastodon, X/Twitter)
- [x] Slack

**Email** mmundt@sandia.gov

**Purpose** Update on deadline

**Content**  https://docs.google.com/document/d/1EQDgRXe9E-pHs8FMTJnoN58vB9rFsk_LUfSgnSiiAQA/edit 

- [x] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
@mrmundt Sophia has sent all of these out!
