### ISSUE TITLE
Add tutorials to website; linked full program but just add the tutorials, including abstracts. due 2024-07-11

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#61]
**Request type**: Website change / addition

**Email** jbtevespro@gmail.com

**Purpose** Add tutorials to website; linked full program but just add the tutorials, including abstracts.

**Content**  https://docs.google.com/document/d/1dZsmt_Inlgf8Tzaje-4JLi1A_px3rCZY8e0WfSygKH4/edit 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by mrmundt** [comment]
@jbteves-sandia - should this also include putting the workshop and BoF abstracts, or no? (Just curious)

**Comment by jbteves-sandia** [comment]
No because I need to make some decisions about reconciling differences in how people followed the template.
