### ISSUE TITLE
Announce travel support program due 2024-08-13

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#83]
**Request type**: 

- [x] Email to conference listserv
- [x] Email to all US-RSE members
- [x] Social media blast (LinkedIn, Mastodon, X/Twitter)
- [x] Slack

**Email** mmundt@sandia.gov

**Purpose** Announce travel support program

**Content**  https://docs.google.com/document/d/1P07nObiIgjbOOEKTDcctzJQ4N8sKF9JdU6254GeAtXk/edit#heading=h.l46gti1amsha 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
All of the listed requests have been fulfilled, but I'm going to leave this open for a bit to make sure we get some of the wider advertising list places.
