### ISSUE TITLE
Advertise the papers and notebooks accepted to the conference due 2024-09-15

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#94]
**Request type**: 

- [ ] Add to monthly US-RSE newsletter
- [x] Social media blast (LinkedIn, Mastodon, X/Twitter)

**Email** diehlpk@lanl.gov

**Purpose** Advertise the papers and notebooks accepted to the conference

**Content**  https://zenodo.org/communities/usrse24/records?q=&l=list&p=1&s=10&sort=newest 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by KristinaRiemer** [comment]
Also going to consider this good at this point
