### ISSUE TITLE
Let attendees know about the three info sessions. due 2024-09-05

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#96]
**Request type**: 

- [x] Email to conference listserv
- [x] Email to all US-RSE members
- [ ] Social media blast (LinkedIn, Mastodon, X/Twitter)
- [x] Slack

**Email** prenticest@ornl.gov

**Purpose** Let attendees know about the three info sessions.

**Content**  https://docs.google.com/document/d/1BwlTL7_httvi92WKkkKOgO72PmfMf2_mOdZH-xx7xmg/edit 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by mrmundt** [comment]
I'll handle the emails because Sophia is out!

**Comment by mrmundt** [comment]
I have scheduled the email to send tomorrow morning at 10AM (I think MT?)

**Comment by KristinaRiemer** [comment]
Remaining social media posts went out Sept 6
