### ISSUE TITLE
To get volunteers! due 2024-09-04

### ISSUE THREAD

**Issue by jsubida** [USRSE/usrse24#99]
**Request type**: 

- [x] Email to conference listserv
- [x] Email to all US-RSE members
- [x] Social media blast (LinkedIn, Mastodon, X/Twitter)
- [x] Slack

**Email** mmundt@sandia.gov

**Purpose** To get volunteers!

**Content**  https://docs.google.com/document/d/1mo8IqUdZlrcioZDtmm3YU9DxakQSPnfegy_C0Zwn5eg/edit 

**Request Drafts** [Google Drive - Request Drafts](https://drive.google.com/drive/folders/16NgJUc6ed3fOWxZssmPrubhf2EdScDC6?usp=share_link)

- [ ] I've informed the requestor that this is complete

**Comment by mrmundt** [comment]
LinkedIn and Email done!
